### ISSUE TITLE
Add support for media keys

### ISSUE THREAD

**Issue by swapnilraj** [shantanuraj/podcst-web#10]
Chrom 73 provides an API for hardware media keys, podcst should leverage this and use this to play and pause podcasts.

**Comment by swapnilraj** [comment]
https://developers.google.com/web/updates/2019/02/chrome-73-media-updates

Link to dev announcement

**Comment by shantanuraj** [comment]
Support for media keys is present now
https://github.com/shantanuraj/podcst-web/blob/09b1ce780067a376fae9b56963a1adcad8c3cf64/src/shared/player/mediaUtils.ts#L51-L69
